% METADATA OF THE FILE
%{ 
    File: BaxterJacobian.m
    Class: Industrial Robotics 
    Authors:
     Elkin Javier Guerra Galeano
     Santiago Garcia Arango
%} 

% Definimos la funcion asociada a evaluar el jacobiano de Baxter
function [J] = BaxterJacobian(dof_0)
    %% Definimos las variables importantes
    % Distancias del robot 
    L1 = 0.06900;
    L2 = 0.36435;
    L3 = 0.06900;
    L4 = 0.37429;
    L5 = 0.01000;
    % Grados de libertad del robot
    t1 = dof_0(1);
    t2 = dof_0(2);
    t3 = dof_0(3);
    t4 = dof_0(4);
    t5 = dof_0(5);
    t6 = dof_0(6);
    t7 = dof_0(7);
    
    % Definimos el jacobiano de Baxter
    J = [- L5*(cos(t5)*(cos(t4)*(cos(t1)*sin(t3) - cos(t3)*sin(t1)*sin(t2)) - cos(t2)*sin(t1)*sin(t4)) + sin(t5)*(cos(t1)*cos(t3) + sin(t1)*sin(t2)*sin(t3))) - L3*(cos(t1)*sin(t3) - cos(t3)*sin(t1)*sin(t2)) - L1*sin(t1) - L4*(sin(t4)*(cos(t1)*sin(t3) - cos(t3)*sin(t1)*sin(t2)) + cos(t2)*cos(t4)*sin(t1)) - L2*cos(t2)*sin(t1),                       L5*(cos(t5)*(cos(t1)*sin(t2)*sin(t4) - cos(t1)*cos(t2)*cos(t3)*cos(t4)) + cos(t1)*cos(t2)*sin(t3)*sin(t5)) - L4*(cos(t1)*cos(t4)*sin(t2) + cos(t1)*cos(t2)*cos(t3)*sin(t4)) - L2*cos(t1)*sin(t2) - L3*cos(t1)*cos(t2)*cos(t3), L5*(sin(t5)*(sin(t1)*sin(t3) + cos(t1)*cos(t3)*sin(t2)) - cos(t4)*cos(t5)*(cos(t3)*sin(t1) - cos(t1)*sin(t2)*sin(t3))) - L3*(cos(t3)*sin(t1) - cos(t1)*sin(t2)*sin(t3)) - L4*sin(t4)*(cos(t3)*sin(t1) - cos(t1)*sin(t2)*sin(t3)),           L5*cos(t5)*(sin(t4)*(sin(t1)*sin(t3) + cos(t1)*cos(t3)*sin(t2)) - cos(t1)*cos(t2)*cos(t4)) - L4*(cos(t4)*(sin(t1)*sin(t3) + cos(t1)*cos(t3)*sin(t2)) + cos(t1)*cos(t2)*sin(t4)),                                        L5*(sin(t5)*(cos(t4)*(sin(t1)*sin(t3) + cos(t1)*cos(t3)*sin(t2)) + cos(t1)*cos(t2)*sin(t4)) - cos(t5)*(cos(t3)*sin(t1) - cos(t1)*sin(t2)*sin(t3))),                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                 0;
            L1*cos(t1) - L3*(sin(t1)*sin(t3) + cos(t1)*cos(t3)*sin(t2)) - L5*(cos(t5)*(cos(t4)*(sin(t1)*sin(t3) + cos(t1)*cos(t3)*sin(t2)) + cos(t1)*cos(t2)*sin(t4)) + sin(t5)*(cos(t3)*sin(t1) - cos(t1)*sin(t2)*sin(t3))) - L4*(sin(t4)*(sin(t1)*sin(t3) + cos(t1)*cos(t3)*sin(t2)) - cos(t1)*cos(t2)*cos(t4)) + L2*cos(t1)*cos(t2),                       L5*(cos(t5)*(sin(t1)*sin(t2)*sin(t4) - cos(t2)*cos(t3)*cos(t4)*sin(t1)) + cos(t2)*sin(t1)*sin(t3)*sin(t5)) - L4*(cos(t4)*sin(t1)*sin(t2) + cos(t2)*cos(t3)*sin(t1)*sin(t4)) - L2*sin(t1)*sin(t2) - L3*cos(t2)*cos(t3)*sin(t1), L3*(cos(t1)*cos(t3) + sin(t1)*sin(t2)*sin(t3)) - L5*(sin(t5)*(cos(t1)*sin(t3) - cos(t3)*sin(t1)*sin(t2)) - cos(t4)*cos(t5)*(cos(t1)*cos(t3) + sin(t1)*sin(t2)*sin(t3))) + L4*sin(t4)*(cos(t1)*cos(t3) + sin(t1)*sin(t2)*sin(t3)),           L4*(cos(t4)*(cos(t1)*sin(t3) - cos(t3)*sin(t1)*sin(t2)) - cos(t2)*sin(t1)*sin(t4)) - L5*cos(t5)*(sin(t4)*(cos(t1)*sin(t3) - cos(t3)*sin(t1)*sin(t2)) + cos(t2)*cos(t4)*sin(t1)),                                       -L5*(sin(t5)*(cos(t4)*(cos(t1)*sin(t3) - cos(t3)*sin(t1)*sin(t2)) - cos(t2)*sin(t1)*sin(t4)) - cos(t5)*(cos(t1)*cos(t3) + sin(t1)*sin(t2)*sin(t3))),                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                 0;
                                                                                                                                                                                                                                                                                                                            0,                                                                               L5*(cos(t5)*(cos(t2)*sin(t4) + cos(t3)*cos(t4)*sin(t2)) - sin(t2)*sin(t3)*sin(t5)) - L2*cos(t2) - L4*(cos(t2)*cos(t4) - cos(t3)*sin(t2)*sin(t4)) + L3*cos(t3)*sin(t2),                                                                                                                 L5*(cos(t2)*cos(t3)*sin(t5) + cos(t2)*cos(t4)*cos(t5)*sin(t3)) + L3*cos(t2)*sin(t3) + L4*cos(t2)*sin(t3)*sin(t4),                                                                                   L4*(sin(t2)*sin(t4) - cos(t2)*cos(t3)*cos(t4)) + L5*cos(t5)*(cos(t4)*sin(t2) + cos(t2)*cos(t3)*sin(t4)),                                                                                                       -L5*(sin(t5)*(sin(t2)*sin(t4) - cos(t2)*cos(t3)*cos(t4)) - cos(t2)*cos(t5)*sin(t3)),                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                 0;
                                                                          - cos(t6)*(sin(t4)*(cos(t1)*sin(t3) - cos(t3)*sin(t1)*sin(t2)) + cos(t2)*cos(t4)*sin(t1)) - sin(t6)*(cos(t5)*(cos(t4)*(cos(t1)*sin(t3) - cos(t3)*sin(t1)*sin(t2)) - cos(t2)*sin(t1)*sin(t4)) + sin(t5)*(cos(t1)*cos(t3) + sin(t1)*sin(t2)*sin(t3))),                                                               sin(t6)*(cos(t5)*(cos(t1)*sin(t2)*sin(t4) - cos(t1)*cos(t2)*cos(t3)*cos(t4)) + cos(t1)*cos(t2)*sin(t3)*sin(t5)) - cos(t6)*(cos(t1)*cos(t4)*sin(t2) + cos(t1)*cos(t2)*cos(t3)*sin(t4)),                                        sin(t6)*(sin(t5)*(sin(t1)*sin(t3) + cos(t1)*cos(t3)*sin(t2)) - cos(t4)*cos(t5)*(cos(t3)*sin(t1) - cos(t1)*sin(t2)*sin(t3))) - cos(t6)*sin(t4)*(cos(t3)*sin(t1) - cos(t1)*sin(t2)*sin(t3)), cos(t5)*sin(t6)*(sin(t4)*(sin(t1)*sin(t3) + cos(t1)*cos(t3)*sin(t2)) - cos(t1)*cos(t2)*cos(t4)) - cos(t6)*(cos(t4)*(sin(t1)*sin(t3) + cos(t1)*cos(t3)*sin(t2)) + cos(t1)*cos(t2)*sin(t4)),                                   sin(t6)*(sin(t5)*(cos(t4)*(sin(t1)*sin(t3) + cos(t1)*cos(t3)*sin(t2)) + cos(t1)*cos(t2)*sin(t4)) - cos(t5)*(cos(t3)*sin(t1) - cos(t1)*sin(t2)*sin(t3))), sin(t6)*(sin(t4)*(sin(t1)*sin(t3) + cos(t1)*cos(t3)*sin(t2)) - cos(t1)*cos(t2)*cos(t4)) - cos(t6)*(cos(t5)*(cos(t4)*(sin(t1)*sin(t3) + cos(t1)*cos(t3)*sin(t2)) + cos(t1)*cos(t2)*sin(t4)) + sin(t5)*(cos(t3)*sin(t1) - cos(t1)*sin(t2)*sin(t3))),                                                                                                                                                                                                                                                 0;
                                                                          - cos(t6)*(sin(t4)*(sin(t1)*sin(t3) + cos(t1)*cos(t3)*sin(t2)) - cos(t1)*cos(t2)*cos(t4)) - sin(t6)*(cos(t5)*(cos(t4)*(sin(t1)*sin(t3) + cos(t1)*cos(t3)*sin(t2)) + cos(t1)*cos(t2)*sin(t4)) + sin(t5)*(cos(t3)*sin(t1) - cos(t1)*sin(t2)*sin(t3))),                                                               sin(t6)*(cos(t5)*(sin(t1)*sin(t2)*sin(t4) - cos(t2)*cos(t3)*cos(t4)*sin(t1)) + cos(t2)*sin(t1)*sin(t3)*sin(t5)) - cos(t6)*(cos(t4)*sin(t1)*sin(t2) + cos(t2)*cos(t3)*sin(t1)*sin(t4)),                                        cos(t6)*sin(t4)*(cos(t1)*cos(t3) + sin(t1)*sin(t2)*sin(t3)) - sin(t6)*(sin(t5)*(cos(t1)*sin(t3) - cos(t3)*sin(t1)*sin(t2)) - cos(t4)*cos(t5)*(cos(t1)*cos(t3) + sin(t1)*sin(t2)*sin(t3))), cos(t6)*(cos(t4)*(cos(t1)*sin(t3) - cos(t3)*sin(t1)*sin(t2)) - cos(t2)*sin(t1)*sin(t4)) - cos(t5)*sin(t6)*(sin(t4)*(cos(t1)*sin(t3) - cos(t3)*sin(t1)*sin(t2)) + cos(t2)*cos(t4)*sin(t1)),                                  -sin(t6)*(sin(t5)*(cos(t4)*(cos(t1)*sin(t3) - cos(t3)*sin(t1)*sin(t2)) - cos(t2)*sin(t1)*sin(t4)) - cos(t5)*(cos(t1)*cos(t3) + sin(t1)*sin(t2)*sin(t3))), cos(t6)*(cos(t5)*(cos(t4)*(cos(t1)*sin(t3) - cos(t3)*sin(t1)*sin(t2)) - cos(t2)*sin(t1)*sin(t4)) + sin(t5)*(cos(t1)*cos(t3) + sin(t1)*sin(t2)*sin(t3))) - sin(t6)*(sin(t4)*(cos(t1)*sin(t3) - cos(t3)*sin(t1)*sin(t2)) + cos(t2)*cos(t4)*sin(t1)),                                                                                                                                                                                                                                                 0;
                                                                                                                                                                                                                                                                                                                            0, - cos(t7)*(sin(t5)*(cos(t2)*sin(t4) + cos(t3)*cos(t4)*sin(t2)) + cos(t5)*sin(t2)*sin(t3)) - sin(t7)*(cos(t6)*(cos(t5)*(cos(t2)*sin(t4) + cos(t3)*cos(t4)*sin(t2)) - sin(t2)*sin(t3)*sin(t5)) + sin(t6)*(cos(t2)*cos(t4) - cos(t3)*sin(t2)*sin(t4))),                                            cos(t7)*(cos(t2)*cos(t3)*cos(t5) - cos(t2)*cos(t4)*sin(t3)*sin(t5)) - sin(t7)*(cos(t6)*(cos(t2)*cos(t3)*sin(t5) + cos(t2)*cos(t4)*cos(t5)*sin(t3)) - cos(t2)*sin(t3)*sin(t4)*sin(t6)), sin(t7)*(sin(t6)*(sin(t2)*sin(t4) - cos(t2)*cos(t3)*cos(t4)) - cos(t5)*cos(t6)*(cos(t4)*sin(t2) + cos(t2)*cos(t3)*sin(t4))) - cos(t7)*sin(t5)*(cos(t4)*sin(t2) + cos(t2)*cos(t3)*sin(t4)), cos(t6)*sin(t7)*(sin(t5)*(sin(t2)*sin(t4) - cos(t2)*cos(t3)*cos(t4)) - cos(t2)*cos(t5)*sin(t3)) - cos(t7)*(cos(t5)*(sin(t2)*sin(t4) - cos(t2)*cos(t3)*cos(t4)) + cos(t2)*sin(t3)*sin(t5)),                                                                                           sin(t7)*(sin(t6)*(cos(t5)*(sin(t2)*sin(t4) - cos(t2)*cos(t3)*cos(t4)) + cos(t2)*sin(t3)*sin(t5)) - cos(t6)*(cos(t4)*sin(t2) + cos(t2)*cos(t3)*sin(t4))), sin(t7)*(sin(t5)*(sin(t2)*sin(t4) - cos(t2)*cos(t3)*cos(t4)) - cos(t2)*cos(t5)*sin(t3)) - cos(t7)*(cos(t6)*(cos(t5)*(sin(t2)*sin(t4) - cos(t2)*cos(t3)*cos(t4)) + cos(t2)*sin(t3)*sin(t5)) + sin(t6)*(cos(t4)*sin(t2) + cos(t2)*cos(t3)*sin(t4)))];                                                                                                                                                                                                                                                                                                                    
    % Definimos el Jacobiano de baxter evaluado con los valores dados
    J = double(J);

end